### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Tarkovskii23** [ilyarolf/AiogramShopBot#1]
Bro, u can make instructions z how to install this shop?

**Comment by ilyarolf** [comment]
> Bro, u can make instructions z how to install this shop?

Hi bro, I'll be sure to let you know once I add a readme.md with a detailed guide on how to deploy the bot.

**Comment by Tarkovskii23** [comment]
Thx bro, i w8

**Comment by Tarkovskii23** [comment]
Bro, u can take me u telegram? Or pm me @hobivaka

**Comment by rukubfab** [comment]
> > Bro, u can make instructions z how to install this shop?
> 
> Hi bro, I'll be sure to let you know once I add a readme.md with a detailed guide on how to deploy the bot.

I'm waiting for this too. It would be great if it works. Thanks for your code.

**Comment by ilyarolf** [comment]
@teletonn , @Tarkovskii23 Hi guys, I've added detailed documentation.
