### ISSUE TITLE
Connection closed by remote host fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists.

### ISSUE THREAD

**Issue by baz0okq** [ilyarolf/AiogramShopBot#20]
Hi mate. Its my first experience with linux and codes. I want learning how to write telegram bots and i found your project. When im trying to do first step "git clone git@github.com:ilyarolf/aiogramshopbot.git -b feature/sqlalchemy-sqlcipher" i got error

kex_exchange_identification: Connection closed by remote host
Connection closed by unknown port 65535
fatal: Could not read from remote repository.
Please make sure you have the correct access rights and the repository exists.

Any idea how to fix it?

**Comment by ilyarolf** [comment]
Hi @baz0okq , have you generated ssh keys? What linux distro are you using?

**Comment by baz0okq** [comment]
I read from many sources that problem with SSH keys but I have no idea how to generate them )))
I use tails.

**Comment by ilyarolf** [comment]
@baz0okq You can generate ssh keys with the command "ssh-keygen"

**Comment by baz0okq** [comment]
I created keys with command
ssh-keygen
Then start ssh agent with command
eval "$(ssh-agent -s)"
After i add keys to ssh agent with command
ssh-add
Now as i understand i should add public key to github and i ****ed up nothing work :(

**Comment by baz0okq** [comment]
I want try add ssh key from terminal to github but i give up.
I write command cat ~/.ssh/id_ed25519.pub and put it through browser and finally cloning repository

**Comment by baz0okq** [comment]
Now i cant do - pip install -r requirements.txt
As i understand i must install python? 
after many attempts i install python 3.9.2 but cant ulgrade it to the 3.12 and after installing python anyway i cant do this command

**Comment by baz0okq** [comment]
Successfully install pip3 and when writing command pip3 install -r requirements.txt
![BF5A78AA-BB1C-4E1D-ADD1-FE7EE9DCC495](https://github.com/ilyarolf/AiogramShopBot/assets/156255251/5c6d9fd9-f4f6-4684-b651-3453fe7cf6c9)

Soon my brain 💥 
Can you tell me which programs should be preinstalled to allow me complete your manual step by step?)

**Comment by ilyarolf** [comment]
@baz0okq All your questions are very superficial and there are answers on google, you can also use phind.com language model to get help at some stage. Everything works fine on python 3.9.6.
