### ISSUE TITLE
RROR: Could not build wheels for ed25519-blake2b, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by donpon34343** [ilyarolf/AiogramShopBot#21]
Hi mate.
Thq for your projectbut i need your help.
Looking many topics and forums in google but nothing help me.
Now i must ask you.

install gcc
install sqlcipher
upgrade setuptools
upgrade wheel
upgrade pip
cloning repo

when installing requiremets have that issue:

Building wheels for collected packages: ed25519-blake2b
  Building wheel for ed25519-blake2b (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      UPDATING build/lib.linux-x86_64-cpython-39/ed25519_blake2b/_version.py
      set build/lib.linux-x86_64-cpython-39/ed25519_blake2b/_version.py to '1.4'
      src/ed25519-glue/ed25519module.c:17:10: fatal error: Python.h: No such file or directory
         17 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ed25519-blake2b
  Running setup.py clean for ed25519-blake2b
Failed to build ed25519-blake2b
ERROR: Could not build wheels for ed25519-blake2b, which is required to install pyproject.toml-based projects

**Comment by ilyarolf** [comment]
Hi, what linux distribution are you using? Do you have a C++ compiler like gcc installed?
https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory

**Comment by donpon34343** [comment]
Im using tails and yes gcc installed

**Comment by ilyarolf** [comment]
Have you tried this command?
`sudo apt-get install python-dev`

**Comment by donpon34343** [comment]
Yes this command help me :)

Bro how can i contact you, i have business offer or add me https://t.me/didluh

**Comment by ilyarolf** [comment]
@donpon34343, I sent you a text message on Telegram
