### ISSUE TITLE
Inline buttons

### ISSUE THREAD

**Issue by turazashvili** [ilyarolf/AiogramShopBot#34]
Hi, created container with docker, set up all as per instructions.
seems like no Inline buttons work. All Keyboard Buttons work properly, but inlines seem not to trigger. Nothing shows up in console logs either.

any suggestions if i'm doing something wrong?

**Comment by ilyarolf** [comment]
Hi @turazashvili, are you using the version with or without database encryption? Which particular inline button is not working for you? 
Try adding a logger on all incoming CallbackQuery, maybe that will give some clue to the solution.

**Comment by turazashvili** [comment]
> Hi @turazashvili, are you using the version with or without database encryption? Which particular inline button is not working for you? Try adding a logger on all incoming CallbackQuery, maybe that will give some clue to the solution.

It looks like it creates buttons correctly, but router doesn't catch any callbacks:
AiogramShopBot | Creating AdminCallback: level=1, action=send_to_everyone, args_to_action=, page=0
AiogramShopBot | Creating AdminCallback: level=4, action=add_items, args_to_action=, page=0
AiogramShopBot | Creating AdminCallback: level=5, action=send_to_everyone, args_to_action=, page=0
AiogramShopBot | Creating AdminCallback: level=6, action=get_db_file, args_to_action=, page=0
AiogramShopBot | Creating AdminCallback: level=7, action=, args_to_action=, page=0
AiogramShopBot | Creating AdminCallback: level=8, action=, args_to_action=, page=0
AiogramShopBot | Creating AdminCallback: level=11, action=, args_to_action=, page=0
AiogramShopBot | Creating AdminCallback: level=14, action=, args_to_action=, page=0
