### ISSUE TITLE
All Categories

### ISSUE THREAD

**Issue by turazashvili** [ilyarolf/AiogramShopBot#35]
When clicking on All Categories gives this error:
AiogramShopBot | ERROR:asyncio:Task exception was never retrieved
AiogramShopBot | future: <Task finished name='Task-15' coro=<BaseRequestHandler._background_feed_update() done, defined at /usr/local/lib/python3.9/site-packages/aiogram/webhook/aiohttp_server.py:136> exception=ValueError("invalid literal for int() with base 10: ''")>
AiogramShopBot | Traceback (most recent call last):
AiogramShopBot |   File "/usr/local/lib/python3.9/site-packages/aiogram/webhook/aiohttp_server.py", line 137, in _background_feed_update    
AiogramShopBot |     result = await self.dispatcher.feed_raw_update(bot=bot, update=update, **self.data)
AiogramShopBot |   File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 188, in feed_raw_update
AiogramShopBot |     return await self.feed_update(bot=bot, update=parsed_update, **kwargs)
AiogramShopBot |   File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 157, in feed_update
AiogramShopBot |     response = await self.update.wrap_outer_middleware(
AiogramShopBot |   File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
AiogramShopBot |     return await handler(event, data)
AiogramShopBot |   File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__       
AiogramShopBot |     return await handler(event, data)
AiogramShopBot |   File "/usr/local/lib/python3.9/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
AiogramShopBot |     return await handler(event, data)
AiogramShopBot |   File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 120, in trigger
AiogramShopBot |     return await wrapped_inner(event, kwargs)
AiogramShopBot |   File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
AiogramShopBot |     return await wrapped()
AiogramShopBot |   File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 275, in _listen_update
AiogramShopBot |     return await self.propagate_event(update_type=update_type, event=event, **kwargs)
AiogramShopBot |   File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
AiogramShopBot |     return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
AiogramShopBot |   File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
AiogramShopBot |     return await self._propagate_event(
AiogramShopBot |   File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 144, in _propagate_event
AiogramShopBot |     response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
AiogramShopBot |   File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
AiogramShopBot |     return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
AiogramShopBot |   File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
AiogramShopBot |     return await self._propagate_event(
AiogramShopBot |   File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 144, in _propagate_event
AiogramShopBot |     response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
AiogramShopBot |   File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
AiogramShopBot |     return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
AiogramShopBot |   File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
AiogramShopBot |     return await self._propagate_event(
AiogramShopBot |   File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 136, in _propagate_event
AiogramShopBot |     response = await observer.trigger(event, **kwargs)
AiogramShopBot |   File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 120, in trigger
AiogramShopBot |     return await wrapped_inner(event, kwargs)
AiogramShopBot |   File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
AiogramShopBot |     return await wrapped()
**AiogramShopBot |   File "/bot/handlers/user/all_categories.py", line 49, in all_categories_text_message
AiogramShopBot |     await all_categories(message)
AiogramShopBot |   File "/bot/handlers/user/all_categories.py", line 85, in all_categories
AiogramShopBot |     category_inline_buttons = await create_category_buttons(0)
AiogramShopBot |   File "/bot/handlers/user/all_categories.py", line 53, in create_category_buttons
AiogramShopBot |     categories = await CategoryService.get_unsold(page)
AiogramShopBot |   File "/bot/services/category.py", line 47, in get_unsold
AiogramShopBot |     stmt = select(Category).join(Item, Item.category_id == Category.id).where(
AiogramShopBot |   File "<string>", line 2, in offset**
AiogramShopBot |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/base.py", line 283, in _generative
AiogramShopBot |     x = fn(self, *args, **kw)
AiogramShopBot |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/selectable.py", line 4091, in offset
AiogramShopBot |     self._offset_clause = self._offset_or_limit_clause(offset)
AiogramShopBot |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/selectable.py", line 3909, in _offset_or_limit_clause        
AiogramShopBot |     return coercions.expect(
AiogramShopBot |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 413, in expect
AiogramShopBot |     resolved = impl._literal_coercion(
AiogramShopBot |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 1093, in _literal_coercion
AiogramShopBot |     value = util.asint(element)
AiogramShopBot |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1364, in asint
AiogramShopBot |     return int(value)
**AiogramShopBot | ValueError: invalid literal for int() with base 10: ''**

**Comment by ilyarolf** [comment]
fixed in #36, check it out for yourself, and give feedback

**Comment by turazashvili** [comment]
it got fixed
