### ISSUE TITLE
Admin panel / Delete Categories

### ISSUE THREAD

**Issue by turazashvili** [ilyarolf/AiogramShopBot#37]
It seems not deleting categoris from admin panel. however it doesn't show up on user side. for subcategories it's fine.
![image](https://github.com/ilyarolf/AiogramShopBot/assets/74835523/02207bc3-0306-466c-b101-c5abdf045418)
![image](https://github.com/ilyarolf/AiogramShopBot/assets/74835523/3d32e17a-7459-4b43-9257-1b9c6cb456b3)
![image](https://github.com/ilyarolf/AiogramShopBot/assets/74835523/90c3c21c-63bb-4069-b08d-bf380e2524f2)

**Comment by ilyarolf** [comment]
Categories in the delete menu may not be deleted for admin. This is done to make the purchase history work properly.
