### ISSUE TITLE
Moving all coins to all deposits to one address?

### ISSUE THREAD

**Issue by jonleach445** [ilyarolf/AiogramShopBot#38]
How would I be able to do this simply?

**Comment by ilyarolf** [comment]
@jonleach445 This can be done if you will be using a cryptocurrency payment provider. But keep in mind that they will charge a commission for this

**Comment by ilyarolf** [comment]
@jonleach445 You can't use one address for each user. You don't need to go through each user's seed phrases from the database, the bot will send you notifications about new top-ups along with the seed phrase.

**Comment by jonleach445** [comment]
Ah, okay, it's quite tedious not just because of that, but because I get hundreds of notifications of each deposit a day that I have to be taking out, it's a lot of work to do manually

**Comment by ilyarolf** [comment]
@jonleach445 in this case, maybe it makes sense for you to develop a script that will auto-withdraw all cryptocurrency from your mnemonic phrases to the same address. But note that it will work only with BTC and LTC, for auto withdrawal of USDT TRC-20 will need TRON. Also USDT TRC-20 transactions do not support multiple inputs.

**Comment by ilyarolf** [comment]
@jonleach445 email me at ilyarolf@mail.ru with your Telegram username and I'll message you on Telegram.

**Comment by ilyarolf** [comment]
**This functionality comes only on a paid basis. At the moment it is implemented to withdraw BTC and LTC deposits of users to one address directly from the bot's admin.
[Buy](https://t.me/ilyarolf_dev).**
