### ISSUE TITLE
Easy way of adding GIFS/Photos to the category page where it shows the subcategories

### ISSUE THREAD

**Issue by kiljorn1109** [ilyarolf/AiogramShopBot#41]
hello, i would like to add a gif/image preview of the product e.g. games, cd keys etc tot the app, so that when u select the category shooters in the subcategory you ll have an image/gif of let s say battlefield/call of duty/doom, is there anything already implemented or should i just go on and start implementing it?

**Comment by ilyarolf** [comment]
@kiljorn1109  Hi, so far there is no functionality for a product card or product gif in the bot. If you need a product card, you can implement it yourself and create a pull request
