### ISSUE TITLE
crypto api feature

### ISSUE THREAD

**Issue by Frazeer14** [ilyarolf/AiogramShopBot#49]
how do I change crypto option to this https://github.com/CrystalPAY-io/python-sdk

**Comment by ilyarolf** [comment]
Hi @Frazeer14, the implementation of this functionality is negotiated separately, and on a commercial basis.

**Comment by Frazeer14** [comment]
telegram??

**Comment by ilyarolf** [comment]
@Frazeer14  send your username or link, I'll message you on telegram

**Comment by Frazeer14** [comment]
@ztxco23

**Comment by ilyarolf** [comment]
@Frazeer14 Texted you on Telegram at 19:00 UTC.

**Comment by 6R1M5L07H** [comment]
Issue still open?
