### ISSUE TITLE
Feature request: add cart workflow

### ISSUE THREAD

**Issue by 6R1M5L07H** [ilyarolf/AiogramShopBot#69]
# User Story
As a customer I want to be able to collect items in a cart and check them out all at once so that I have a good overview of my purchases from my "shopping spree".

# Reason
It is not only pretty common to have a cart workflow in place in a shopping system, but it would also make it easier to accumulate orders which will make it easier for the shop owner to fullfill the orders.

# Proposal for solution
Add a Cart containing CartItems to the shop system and integrate the cart into the purchase workflow

# Solution design
1) add a model "Cart"
2) add "CartItems" to the "Cart" containing the information from "item" and "subcategory" in an entity
3) add a confirmation step if a customer wants to buy all CartItems in the Cart
4) continue with the existing buy workflow on confirmation

**Comment by ilyarolf** [comment]
Merged in #63
